/**
 * This file is autogenerated. If you want to change it, you can
 * but it will be overriden on the next generation
 */
import jsonSchema from './schema.json';
import createValidator from '@shared/validate-json';

const validate = createValidator(jsonSchema);

export default validate;
